### ISSUE TITLE
Unable to compile the brain simulator

### ISSUE THREAD

**Issue by misgeatgit** [GoodAI/BrainSimulator#10]
Hi guys, It has been long time since I used VS and am having the following missing dependencies error
``
  The type or namespace name 'OpenTK' could not be found (are you missing a using directive or an assembly reference?)
  The type or namespace name 'YAXLib' could not be found (are you missing a using directive or an assembly reference?)
  The type or namespace name 'ManagedCuda' could not be found (are you missing a using directive or an assembly reference?)
 The type or namespace name 'ICustomSerializer' could not be found (are you missing a using directive or an assembly reference?)	
``

**Comment by misgeatgit** [comment]
Alright, the readme file doesn't tell that one has to do  **git submodule init** and **git submodule update** . After doing so, build has succeeded.

**Comment by PremekPaska** [comment]
Thanks, added to the README.
