### ISSUE TITLE
Cannot find *.ptx files

### ISSUE THREAD

**Issue by misgeatgit** [GoodAI/BrainSimulator#11]
While trying to load .brain project files in to the simulator,  cannot find *.ptx file  exception is thrown. Where are these files?

**Comment by PremekPaska** [comment]
These files are CUDA kernels (an intermediate representation that is compiled for the concrete GPU they're running at).

I'm assuming you are running Brain Simulator from the sources. Is it correct?

The files should be in directories for individual modules within the BrainSimulator binary directory, for example BasicNodes have the ptx files here (replace Debug for Release if you run it in Release):
Sources\Platform\BrainSimulator\bin\Debug\modules\GoodAI.BasicNodes\ptx

In each module project, there's a post_build.cmd script that should copy these files inside the BrainSimulator bin directory.

See Sources\Modules\BasicNodes\Module\post_build.cmd

Was it helpful?

**Comment by misgeatgit** [comment]
Hi @PremekPaska ,
>I'm assuming you are running Brain Simulator from the sources. Is it correct?
Yes I am running it from source in Debug mode. The I was opening the .brain files from  the other repo called BrainSimulatorSampleProjects and where there was no post_buld.cmd script. However, As you mentioned, there are three Mdules under Sources dir which have the post_build.cmd file. 

Saying the above, I am not still clear how to resolve the issue. If I am not mistaken opening one of the .brain files from  BrainSimulatorSampleProjects  in the brain simulator with out any farther steps should work. Right?

**Comment by PremekPaska** [comment]
Yes, samples should work (unless marked as obsolete -- there's just one such sample).

Did you build BrainSim from sources? If yes, please check if there are at least some ptx files in the directory mentioned above.
