### ISSUE TITLE
On which branch to fix Spelling Errors

### ISSUE THREAD

**Issue by J-F-B-M** [GoodAI/BrainSimulator#13]
Title is topic. As you might have seen I have fixed **_standart**_ in a few places, creating pull-requests all over the place. This wasn't very thought through, so I stopped after the third or fourth PR.
I noticed I pushed one to _master_ and one to _develop_. While no real issue by itself, it might in a rare occurence disturb Gits workflow (no expert, just imagining the worst).

So my question: On which of those two branches is a direct file-edit from the GitHub-Website best made?

In my personal fork of the BrainSimulator-Repository I think I now found out how to _not_ spam PRs but instead create a single big one, but I do not always have easy access to it (for example on other computers).

**Comment by PremekPaska** [comment]
Please wait for the next source release (it will probably be this month), and base your fixes there. Please put all related documentation fixes in one branch based on the master branch.

GitHub website edits are not the best, but the commits can be cherry-picked when necessary.
