### ISSUE TITLE
Spelling Error in Node Help

### ISSUE THREAD

**Issue by J-F-B-M** [GoodAI/BrainSimulator#5]
MyRandomNode
Author: GoodAI
Status: Working

[...]

MyRNGTask - Generate random numbers
This task will generate your **rundom** numbers.

---

Should be **random** instead of **rundom**.

---

BrainSimulator/Sources/Modules/BasicNodes/Module/Common/MyRandomNode.cs
Line 82

https://github.com/GoodAI/BrainSimulator/blob/e8d489bdf76a317db9ff9f26a98cc26676f2226a/Sources/Modules/BasicNodes/Module/Common/MyRandomNode.cs

**Comment by J-F-B-M** [comment]
For future spelling errors: How can I solve them myself without poking a contributor and without forking the whole thing?

**Comment by PremekPaska** [comment]
Fixed, thanks!

(Hopefully, there will not be so many typos.-)
