### ISSUE TITLE
Can't open solution in Visual Studio 2015 Community

### ISSUE THREAD

**Issue by sorrge** [GoodAI/BrainSimulator#6]
The projects BasicNodesCuda and XmlFeedForwardNetCuda don't load, showing the error in the output:
BrainSimulator\Sources\Modules\BasicNodes\Cuda\BasicNodesCuda.vcxproj : error  : One or more errors occurred.
BrainSimulator\Sources\Modules\XmlFeedForwardNet\Cuda\XmlFeedForwardNetCuda.vcxproj : error  : One or more errors occurred.

**Comment by MartinBalek** [comment]
Unfortunately nVidia does not support CUDA for VS2015 yet:
https://devtalk.nvidia.com/default/topic/850491/cuda-and-visual-studio-2015/
http://docs.nvidia.com/cuda/cuda-getting-started-guide-for-microsoft-windows/index.html#abstract
To compile CUDA parts, you need to use VS2013. 

In theory you can compile all kernels using nvcc and place resulting ptx files to proper folders, but it would be quite tedious.

**Comment by sorrge** [comment]
Ah, I see. Thanks.
