### ISSUE TITLE
AI Interaction

### ISSUE THREAD

**Issue by Deathlymad** [GoodAI/BrainSimulator#7]
ONe Thing up front:
I love the project and I am really interested in AIs, however I am not an expert.
SO My question/Proposal is a module anabeling AI's to share knowledge through communication enabling them to solve multiplayer tasks. I believe that communication is the most crucial thing for the human society. 

Deathlymad, an interested developer

P.S.:I am wonder if you would allocate a CUDA shared memory sedction and let two AIs Read/Write to if if they would be able to figure out how to communicate with ach other.

**Comment by PremekPaska** [comment]
Hi, thanks for your suggestions.

I see two ways to make two AIs communicate:
1) The simplest one: you can have two AIs in a single project.
2) You can write a module that implements communication over network (or even a shared memory).

Premek
